---
title: "Introduction to autobeale"
author: "Steve Westenbroek"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to autobeale}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Overview

This document demonstrates the basic use of the autobeale package. The code is broken into a number of discrete functions, which may be thought of as pertaining to either the Beale calculation itself, or else to the partitioning and stratification of the dataset *prior* to calculation with the Beale method.

## Background

The Beale Ratio Estimator has been used in numerous nutrient and pollutant loading studies, particularly for load estimates to the Great Lakes. The `autobeale` package traces its roots back earlier versions of software aimed at making these calculations easier. Peter Richards, the author of an earlier `AutoBeale` code has written about the 
evolution of Beale software over the years:

> The Beale Ratio Estimator is described in Tin (1965). It has been widely used for computation of
 substance loadings to receiving waters, particularly in the Great Lakes system. The initial code was
 developed by Ken Baun of Wisconsin DNR (1982). It was subsequently used and developed by Kevin McGunagle
 at the International Joint Commission (IJC), from whom the current version was received. It was then
 developed in the 1990’s by Pete Richards at the National Center for Water Quality Research
 at Heidelberg University (www.heidelberg.edu/academiclife/distinctive/ncwqr). Peter developed the code
 to work with the Macintosh computer of the time (“Motorola" architecture, which was replaced by
 Intel architecture ca. 2005), and included a Graphic User Interface (GUI) and an algorithm that 
 objectively and sequentially searched out the best stratification given the data, with “best” being defined as
 minimizing the root-mean-square error (RMSE) given the data at hand.

This package consists of the `beale` function, which calculates the bias-corrected load for a give set of input, and a number of supporting classes aimed at storing information on partitions and data stratrums.
