#' Discharge and nitrate-nitrite concentration data for Rocky River, Ohio.
#'
#' A dataset that contains discharge and nitrate-nitrite concentration data
#'  from 1997 for the Rocky River, Ohio.
#'
#' @format A data frame with 365 rows and 3 variables:
#' \describe{
#'   \item{date}{date, as an R data class}
#'   \item{discharge_cfs}{daily mean discharge, in cubic feet per second}
#'   \item{discharge_cms}{daily mean discharge, in cubic meters per second}
#'   \item{concentration_mg_L}{concentration of nitrate-nitrite, in milligrams per liter}
#' }
"qcdata"

#' Load calulation results from the original AutoBeale program.
#'
#' A dataset that contains load calculation results as generated by the original AutoBeale
#' program for 1997 for the Rocky River, Ohio.
#'
# ' @format A data frame with 365 rows and 3 variables:
# ' \describe{
# '   \item{date}{date, as an R data class}
# '   \item{discharge}{daily mean discharge, in cubic feet per second}
# '   \item{concentration}{concentration of nitrate-nitrite, in milligrams per liter}
# ' }
"ab"

#' Daily load calculation results from the original AutoBeale program.
#'
#' A dataset that contains *daily* load calculation results as generated by the original AutoBeale
#' program for 1997 for the Rocky River, Ohio.
#'
# ' @format A data frame with 52 rows and 5 variables:
# ' \describe{
# '   \item{date}{date, as an R data class}
# '   \item{load_g_day}{daily calculated load in grams per day}
# '   \item{q_cms}{daily mean discharge, in cubic meters per second}
# '   \item{q_cfs}{daily mean discharge, in cubic feet per second}
# '   \item{concentration_mg_L}{NO2-NO3 concentration, in milligrams per liter}
# '   \item{load_kg_day}{daily calculated load, in kilograms per day}
# ' }
"daily_loads"
